"""The map the video draws, from the same cached files the dashboard uses: no network.

    pnpm video:data

Writes video/src/data/map.json: the 22–23 July hotspots, the forecast that first put La Atalaya in the
fire's path, the zones, the main roads, the safe points and two cached routes (a resident's way out
and the crew's way in). Run from backend/ with its environment, so routes come from app.evacuation
exactly as the dashboard gets them.
"""

import json
from datetime import UTC, datetime
from pathlib import Path

from shapely import affinity
from shapely.geometry import mapping, shape

from app import evacuation, geo, scenario
from app.config import DATA_DIR
from app.models import Neighbor, TravelMode

OUT = Path(__file__).resolve().parents[1] / "src" / "data" / "map.json"
# The replay starts here; every time in the file is minutes after it.
EPOCH = datetime(2026, 7, 22, 0, 0, tzinfo=UTC)
UNTIL = datetime(2026, 7, 24, 0, 0, tzinfo=UTC)
BOX = (-4.85, 40.30, -4.38, 40.50)
GRID = 0.0015  # about 130 m: one dot per cell, the first time it burned
SAFE_POINT = "san-martin"
# The demo autopilot's call with the household that needs rescue (data/demo_timeline.json).
CALL_AT = datetime(2026, 7, 23, 14, 35, tzinfo=UTC)


def minutes(at: datetime) -> int:
    return round((at - EPOCH).total_seconds() / 60)


def parse(text: str) -> datetime:
    return datetime.fromisoformat(text.replace("Z", "+00:00"))


def rounded(coords):
    if isinstance(coords[0], (int, float)):
        return [round(coords[0], 5), round(coords[1], 5)]
    return [rounded(c) for c in coords]


def lines(geometry, tolerance: float) -> list:
    simple = shape(geometry).simplify(tolerance, preserve_topology=True)
    parts = simple.geoms if hasattr(simple, "geoms") else [simple]
    out = []
    for part in parts:
        if part.geom_type == "Polygon":
            out.append(rounded(list(part.exterior.coords)))
        else:
            out.append(rounded(list(part.coords)))
    return out


def buffered_km(geometry, km: float):
    """The geometry grown by `km`, measured on the ground (degrees of longitude are shorter here)."""
    squash = 1 / 111.32 / 0.7615  # km to degrees of longitude at 40.4° N
    stretch = 111.32 * 0.7615
    flat = affinity.scale(shape(geometry), xfact=stretch, yfact=110.57, origin=(0, 0))
    grown = flat.buffer(km, quad_segs=16)
    return affinity.scale(grown, xfact=squash, yfact=1 / 110.57, origin=(0, 0))


def inside(lon: float, lat: float) -> bool:
    return BOX[0] <= lon <= BOX[2] and BOX[1] <= lat <= BOX[3]


def hotspots() -> list:
    first: dict[tuple[int, int], tuple[int, float, float]] = {}
    for feature in json.loads((DATA_DIR / "hotspots_2026-07-22_24.geojson").read_text())["features"]:
        lon, lat = feature["geometry"]["coordinates"]
        at = parse(feature["properties"]["observed_at"])
        if not inside(lon, lat) or at >= UNTIL:
            continue
        cell = (round(lon / GRID), round(lat / GRID))
        t = minutes(at)
        if cell not in first or t < first[cell][0]:
            first[cell] = (t, lon, lat)
    return sorted([[round(lon, 4), round(lat, 4), t] for t, lon, lat in first.values()], key=lambda h: h[2])


def closed_stretches(zones: list[dict]) -> list:
    area = evacuation.fire_m(CALL_AT, evacuation.AVOID_AHEAD_H).buffer(150)
    stretches = []
    for f in zones:
        if f["properties"]["kind"] != "road":
            continue
        cut = geo.to_metres(shape(f["geometry"])).intersection(area)
        if cut.is_empty:
            continue
        stretches.extend(lines(mapping(geo.to_degrees(cut)), 0.0004))
    return stretches


def main() -> None:
    lead = json.loads((DATA_DIR / "lead_time_la-atalaya.json").read_text())
    flagged = parse(lead["flagged_at"])
    zones = json.loads((DATA_DIR / "zones.geojson").read_text())["features"]
    spread = json.loads((DATA_DIR / f"spread_2026-07-23.geojson").read_text())["features"]
    places = json.loads((DATA_DIR / "places.json").read_text())
    residents = [Neighbor(**n) for n in json.loads((DATA_DIR / "neighbors.sample.json").read_text())]

    # The resident whose call the video shows needs rescue: the crew's way in goes to them. The way out
    # to the safe point the approved order names is a neighbour's, who leaves on their own.
    resident = next(n for n in residents if n.id == "n03")
    evacuee = next(n for n in residents if n.id == "n01")
    target = next(p for p in evacuation.all_places() if p.id == SAFE_POINT)
    way_out = evacuation.route_to(evacuee, target, TravelMode.CAR, scenario.current().scenario_time)
    way_in = evacuation.rescue_route(resident, scenario.current().scenario_time)

    data = {
        "about": "Generated by video/scripts/export_map.py from data/. Times are minutes after 2026-07-22 00:00 UTC.",
        "box": BOX,
        "hotspots": hotspots(),
        "leadTime": {
            "flagged": minutes(flagged),
            "reached": minutes(parse(lead["reached_at"])),
            "minutes": lead["minutes"],
            "radiusKm": lead["radius_km"],
            # The area the first hotspot had to reach: La Atalaya grown by the radius.
            "ring": lines(buffered_km(next(f for f in zones if f["properties"]["id"] == lead["zone"])["geometry"], lead["radius_km"]), 0.0005),
        },
        "forecast": {
            "issued": minutes(flagged),
            "hours": [
                {"hour": f["properties"]["hour"], "rings": lines(f["geometry"], 0.0008)}
                for f in spread
                if parse(f["properties"]["issued_at"]) == flagged
            ],
        },
        "zones": {
            f["properties"]["id"]: {"name": f["properties"]["name"], "rings": lines(f["geometry"], 0.0002)}
            for f in zones
            if f["properties"]["kind"] in ("estate", "town")
        },
        "roads": [
            {"name": f["properties"].get("name"), "lines": lines(f["geometry"], 0.0006)}
            for f in zones
            if f["properties"]["kind"] == "road"
        ],
        # The stretches of road closed to residents at the moment of the video's call: inside the area
        # their routes avoid (burned plus the next hour of forecast, evacuation.fire_m), the dashboard's
        # dashed cordon (frontend/src/domain/zones.ts closedRoads) cut down to where the fire is.
        "closedStretches": closed_stretches(zones),
        # Where the video shows the coordinator closing a road by hand: on the AV-502, away from both
        # routes, so the routes drawn are ones that go around it.
        "closure": {"lon": -4.44014, "lat": 40.39546, "road": "AV-502"},
        "places": [
            *({"id": p["id"], "name": p["name"], "lon": p["lon"], "lat": p["lat"], "kind": "safe"} for p in places["safe_points"]),
            {**{k: places["crew_base"][k] for k in ("id", "name", "lon", "lat")}, "kind": "crew"},
        ],
        "residents": [{"id": n.id, "lon": n.lon, "lat": n.lat, "zone": n.zone} for n in residents],
        "resident": resident.id,
        "routes": {
            "wayOut": {"to": target.name, "minutes": round((way_out.duration_s or 0) / 60), "line": rounded(way_out.geometry["coordinates"])},
            "wayIn": {"minutes": round((way_in.duration_s or 0) / 60), "line": rounded(way_in.geometry["coordinates"])},
        },
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(data, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
    print(f"{OUT.relative_to(Path.cwd().parent)}: {len(data['hotspots'])} hotspots, {OUT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
