// The mini-demo's script: when each thing happens, in seconds of a ~25 s loop. The map data
// (miniDemo.json) is real and generated by scripts/mini-demo-data.mjs; the residents' outcomes
// and the call are examples, and the page says so.

import type { TriageStatus } from '../../domain/triage'
import { HOTSPOT_AGE_COLORS } from '../theme'
import data from './miniDemo.json'

export const MINI = data

export const LOOP_SECONDS = 25.5
/** When each of the four steps starts. */
export const STEP_STARTS = [0, 7, 11, 17] as const
/** The moment that sums each step up, shown under reduced motion or after a jump while paused. */
export const STEP_FRAMES = [6.9, 10.9, 16.9, 24] as const

/** 00:00 CEST on 23 July 2026, the zero of the data's minutes. */
export const DAY_START = Date.parse('2026-07-22T22:00:00Z')

/** The loop, and the frame shown before it plays, open at 14:30, when the fire already fills the map's west. */
const OPENING_MINUTE = 14 * 60 + 30

// Seconds of the loop to minutes of 23 July: fast through the early afternoon, slow around the calls.
const CLOCK: readonly (readonly [seconds: number, minute: number])[] = [
  [0, OPENING_MINUTE],
  [7, MINI.flaggedMinute],
  [11, MINI.flaggedMinute + 30],
  [17, MINI.flaggedMinute + 70],
  [23, 1310],
  [LOOP_SECONDS, 1310],
]

export function minuteAt(seconds: number): number {
  for (let i = 1; i < CLOCK.length; i++) {
    const [s1, m1] = CLOCK[i]
    const [s0, m0] = CLOCK[i - 1]
    if (seconds <= s1) return m0 + ((seconds - s0) / (s1 - s0)) * (m1 - m0)
  }
  return CLOCK[CLOCK.length - 1][1]
}

export function stepAt(seconds: number): number {
  let step = 0
  STEP_STARTS.forEach((start, index) => {
    if (seconds >= start) step = index
  })
  return step
}

/** The hotspot colour for its age in hours, as on the dashboard's map. */
export function hotspotColor(ageHours: number): string {
  let color = HOTSPOT_AGE_COLORS[0][1]
  for (const [hours, stop] of HOTSPOT_AGE_COLORS) if (ageHours >= hours) color = stop
  return color
}

/** The call, line by line: who speaks, the locale key, and when the typing starts and ends. */
export const CALL_LINES = [
  { who: 'agent', key: 'agentLine', from: 11.3, to: 13.5 },
  { who: 'agent', key: 'agentAsk', from: 13.8, to: 14.7 },
  { who: 'resident', key: 'residentLine', from: 15.1, to: 16.3 },
] as const

/** Example outcomes: which resident (by index in MINI.residents) ends in which state, and when. */
export const OUTCOMES: readonly { resident: number; status: TriageStatus; at: number }[] = [
  { resident: 2, status: 'needs_rescue', at: 17.4 },
  { resident: 0, status: 'evacuating', at: 18.2 },
  { resident: 1, status: 'no_answer', at: 19 },
  { resident: 3, status: 'evacuating', at: 19.8 },
  { resident: 4, status: 'evacuating', at: 20.6 },
]

/** The evacuee's route draws from `from` to `to`; the crew's route likewise. */
export const EVACUATION_DRAW = { from: 18.2, to: 20.6 }
export const CREW_DRAW = { from: 17.6, to: 20.2 }
/** The predicted spread and the zones in its path appear here. */
export const CONE_AT = 7
export const ZONES_AT = 8

export const progress = (seconds: number, span: { from: number; to: number }) =>
  Math.min(1, Math.max(0, (seconds - span.from) / (span.to - span.from)))
